package:
    name:           hipanel-module-finance
    namespace:      hipanel\modules\finance
    headline:       HiPanel Finance Module
    title:          Finance Plugin for HiPanel
    type:           yii2-extension
    keywords:       finance, hipanel, plugin
    year:           2014
    description:    |
        [![Logo](https://raw.githubusercontent.com/hiqdev/hipanel-core/master/docs/logo.png)](https://hipanel.com/)

        [HiPanel](http://hipanel.com) is the next generation control panel for hosting, domains and more.

        This package provides financial functions for HiPanel:
            * bills, invoices, tariffs and so on
            * payment systems integration with [yii2-merchant](https://github.com/hiqdev/yii2-merchant)
            * shopping cart with [yii2-cart](https://github.vom/hiqdev/yii2-cart)

require:
    hiqdev/hidev-config:        "*"
    hiqdev/hidev-config-php:    "*"
